import { fileURLToPath } from 'node:url';
// Build-time validation: fails the build if any labelled room is off by > 10 mm
// or the plan topology is broken. Writes reports/DIMENSION_REPORT.md.
import { writeFileSync, mkdirSync } from 'node:fs';
import { runAll, dimensionMarkdown } from '../src/data/validate.ts';

const { ok, rows, topo } = runAll();
console.log('\n=== DIMENSION VALIDATION (tolerance 10 mm) ===');
for (const r of rows) {
  console.log(`${r.pass ? 'PASS' : 'FAIL'}  ${r.name.padEnd(18)} req ${r.reqEW.toFixed(4)} x ${r.reqNS.toFixed(4)}  act ${r.actEW.toFixed(4)} x ${r.actNS.toFixed(4)}  err ${(r.errEW * 1000).toFixed(1)}/${(r.errNS * 1000).toFixed(1)} mm`);
}
console.log('\n=== TOPOLOGY ===');
topo.errors.forEach((e) => console.log('ERROR  ' + e));
topo.warnings.forEach((e) => console.log('WARN   ' + e));
topo.info.forEach((e) => console.log('info   ' + e));

const reportDir = fileURLToPath(new URL('../../reports/', import.meta.url));
mkdirSync(reportDir, { recursive: true });
const md = `# Dimension Report

Generated by \`npm run validate\` (scripts/validate.mjs) from \`src/data/floorplan.ts\` on ${new Date().toISOString()}.

Tolerance: ±10 mm on every explicitly dimensioned room. Dimensions are clear internal sizes measured
face-to-face of the bounding walls (or, for open-plan zones, the labelled-zone rectangle defined in the
floor-plan data and bounded by the nearest wall or fixed-joinery line).

Overall result: **${ok ? 'PASS' : 'FAIL'}** — ${rows.filter((r) => r.pass).length}/${rows.length} rooms within tolerance, ${topo.errors.length} topology errors.

${dimensionMarkdown(rows)}

## Topology checks

${topo.errors.length ? topo.errors.map((e) => '- ERROR: ' + e).join('\n') : '- No wall overlaps, no floor-finish overlaps, all openings inside their walls, all door openings ≥ 0.76 m.'}
${topo.warnings.map((e) => '- WARN: ' + e).join('\n')}
${topo.info.map((e) => '- ' + e).join('\n')}
`;
writeFileSync(reportDir + '/DIMENSION_REPORT.md', md);
if (!ok) {
  console.error('\n!!! VALIDATION FAILED — fix src/data/floorplan.ts before building !!!\n');
  process.exit(1);
}
console.log('\nValidation OK.\n');
